language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build -t ivanslavchev/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ivanslavchev/docker-react npm run test